# ??????
spring.application.name = test
server.port= 8090

# Nacos ?????????? Nacos ??
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

# Nacos ???????? Nacos ??????
# ??1???? Nacos ?????? Nacos ???????????????
# spring.config.import=nacos:${spring.application.name}.properties?group=DEFAULT_GROUP

# ??2???? Nacos ?????? Nacos ??????????????
#spring.config.import=optional:nacos:${spring.application.name}.properties?group=DEFAULT_GROUP

# ?????? Nacos ??????????????1??????2???????
 spring.cloud.nacos.config.import-check.enabled=false

spring.cloud.sentinel.eager=true
spring.cloud.sentinel.transport.dashboard=localhost:8080