# configuration for alipay sandbox environment
alipay:
  protocol: https
  gateway-host: openapi-sandbox.dl.alipaydev.com

  sign-type: RSA2
  app-id: 9021000157696818
  merchant-private-key: >
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrsoIIWCUS/Je0Yq20/bMkMd1g2LefRrnIuYRq10CKiL9wcN1uGtPGOyt/LMrpXBjG4mVjL410WXsqLGIdjHZyXAfLZBgbQNIqx2eOMGTii2pkSFWJewJHPq+ZNXhctNEAG2LGuUo0DtDnvWOkZr5Hdf5niOcoR/LM+2/8TdtS3kdMRY/evxBI+SHNJ2k0CTTXuvivCz3gQ0LeB7HJlOQ9Sw8DjalHVPgrE3gFvCEp8+Um8BD7D4cY5EgcoSNoO+EY+o9zy8HcTYfLVFZPBnev0Vd/k1D6RF9ziVab9EyViljw0xTNDrnGKF7IE7WMQVDAdiq2HOtFIs1s/YgXB4ShAgMBAAECggEAFP7ZI8gTkITO0EIY178GPvDSD1uw6IsvgLoe1SnJPKeIMWm7yhEBwIXPxddmYK7gYMGigER6WbXvd7LBtLdObKGQWnC8+egtSwnjQeHtFD7UHbsyqoMePjQOKP/+3edGf2rZ408ZIdCF/zCLlLjzn61wFJ0LF0PlDufYQ9QJc9KDOFvIh8FYzXZAUMjJ+wEYJ1KDD0pCHR2iuiS/D0RrtIGyNaC/q/jdcLeYxKpjX26qz5WeIEOzYWkIUr6xnp3tczYjFJivXCfs7GQdJrmsgQjwyvD9rjY8sWKwYSTllvl8Xq1r6umpZM+Lh9fFDY0hJVP+klKQD8w+qY+eyWc+oQKBgQDaV8v4z9p+YUYJeMKCXJkvUu4EHJ9PYUFLQGfN4rlh0QdzRqskbEEs0xqJ3MfufFwDFZQxYMuOscVoZEjhdls7h6d9jz6Xpjrr8zBjREaN5ZBX/Ta1poSOCiRKoaN8A/wgWYtoKFZC2OB5Tnb48CRKYsx2HBR7D949/cLsCQoVvQKBgQDJTzpgUhtunOqvVAoXmEgeS0esIQq2fHXNM3WOzWH2isIFLMlONVWN1Sj9nM9lqqc1Xra7UV/mmz18ICFuDLmb4lkQ6TkGiOUFog7RJ4lw9HAW1Qo8KMFSirNA4e76e7w90xYDpgMDJXjznSgMXS18Wk3mvmm6To7InuFpGmIetQKBgF47+EeJhdZ3qx+ZY/GZf2+iTiGuLL+4zNJqmKKOUM47xghlnqWYp0RuVAzeIdf3Cks2fAAXs6MBbJ7ScXYFe/ikYpBZS31t/A4rpl2hcQX65yJiocMifCFFlUY0nvd+TMm1e+pXRmuRaMhSKhzkn/UO0QnEsr4uKg/9PqxadmTNAoGAAVR9rT89oSh2QHxMqMU/zLtwmMmLGZOO77EkWLIwsIFQMNqP5e1iSFKdN7e+gwxymF6s1GYAPTTPXi+UKPb6jvYa4oq37rwezz+321foh4+F4hC8RZN7W4FBF++mNY91ue7YGWQSZwXrW6ixKAvBji3Gj/y4FBwKw3aRRLGA7nUCgYEAg+/eZgpuLvyP8Y/l4lbp+39X6LEA7SKWZGTkJWbxb8bBifyFwnT3WNSa4Rk/BoxgsTn2Ogt8/DBUo18aC653Wc+DyyXd07EKv55cPW1Acydok4O95/pvLnUnvimxwZqbpv2Yht3n8UV6d0tplMfwkZ/Hf3bSVYePh7qLgvxF5AA=
  alipay-public-key: >
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnVr9uF0w/K1RDiKDKF72dgHuZtvYFRoF7yuyRz+1VxBJeKb2Mvfn02i48sfcLY2MerJK65gQCUPgUz8efxvKBBzT4uRQJycPaJEvuE4Pg5/gX8ya57S3lPxQ570WI0MnqvCsfMs4ZTH3d+VE4BS7MbMWsIwm7WWHNjNnHfYAUgFb6K1mJ0j9h0fqn3OOKfRP5oWkAkll5MmJtU1cD3Ao2Sd3p+7STgqFYTFmRsH6gQRXHCJM7iAKyXtI5JdbwcfN2vnA7Btg9/j7BGXn3awCAAM9fSfslRK13upjm+gCe06iarBgdX1eyeBpAsY86waUDjeiLNMkaSIQ1OMTFF63+wIDAQAB

  # here must be with a public ip address or use NAT
  notify-url: http://x36727f9.natappfree.cc/pay/alipay/notify

  #？
  return-url: http://localhost:8080/#/pay-success


  payee-type: ALIPAY_LOGON_ID    # 或 ALIPAY_USER_ID 就用商户id
  payee-account: dqotky2423@sandbox.com  # 你的沙箱收款账号
  payee-name: dqotky2423     # 可选，部分接口支持校验实名