<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>ruoyi</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>3.9.0</version>
    </parent>

    <artifactId>platform</artifactId>
    <name>platform</name>

    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <!-- 通用工具-->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Protobuf 4.33.0 依赖（与生成代码版本一致） -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>4.32.1</version>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.41.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

<!--        &lt;!&ndash; HanLP（中文处理） &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.hankcs</groupId>-->
<!--            <artifactId>hanlp</artifactId>-->
<!--            <version>portable-1.8.4</version>-->
<!--        </dependency>-->

        <!--   下面俩个依赖用于骑手端的身份证图片识别身份证号码     -->
        <!-- OpenCV Dependency -->
<!-- TODO        <dependency>-->
<!--            <groupId>org.opencv</groupId>-->
<!--            <artifactId>opencv</artifactId>-->
<!--            <version>4.5.1</version>-->
<!--        </dependency>-->

        <!-- Tesseract OCR Dependency -->
        <dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>5.0.0</version>
        </dependency>


    </dependencies>
</project>